spring.application.name=TraineeAPI

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.root=INFO
logging.level.com.example.TraineeAPI=DEBUG

server.port=8087
