version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: EmployeeDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TIGER
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  traineeapi:
    build: .
    container_name: traineeapi
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/EmployeeDb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: TIGER
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs


volumes:
  pgdata:
